export { default as addClass } from './src/add-class';
export { default as applyStyles } from './src/apply-styles';
export { default as closest } from './src/closest';
export { default as contains } from './src/contains';
export { default as currentValue } from './src/current-value';
export { default as hasClass } from './src/has-class';
export { default as matches } from './src/matches';
export { default as removeClass } from './src/remove-class';
export { default as removeStyle } from './src/remove-style';
export { default as removeStyles } from './src/remove-styles';
export { default as selectorContains } from './src/selector-contains';
export { default as setStyle } from './src/set-style';
export { default as supportedByElement } from './src/supported-by-element';
export { default as supportedProps } from './src/supported-props';
export { default as supported } from './src/supported';
export * from './src/types';